# Generated by Django 4.2.6 on 2023-10-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='securitydata',
            fields=[
                ('securityID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('securityName', models.TextField(max_length=200)),
                ('securityIC', models.CharField(max_length=200)),
                ('securityNophone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='securityIncident',
            fields=[
                ('incidentID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('incidentDate', models.CharField(max_length=200)),
                ('incidentLoc', models.TextField(max_length=200)),
                ('incidentDesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('visitorName', models.TextField(max_length=200)),
                ('visitorIc', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('visitorPhone', models.CharField(max_length=200)),
                ('visitorDate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='securityShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftDate', models.CharField(max_length=200)),
                ('startTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
                ('Shiftdesc', models.TextField(max_length=200)),
                ('securityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securitymanagement.securitydata')),
            ],
        ),
    ]
